### ISSUE TITLE
Version History without Reverting

### ISSUE THREAD

**Issue by collimarco** [laserlemon/vestal_versions#1]
You should be able to get a specific version of a model (for example to display it) without necessarily revert it.

**Comment by geetarista** [comment]
Isn't that what the revert_to (as opposed to revert_to!) does? This changes the record to the specific version you want without saving it.

**Comment by laserlemon** [comment]
The `revert_to` method reverts the models attributes without saving. You can also arbitrarily access any single version's changes using the following:

```
# x is a version number, date/time or symbol    
version = model.versions.at(x)
```

You then have access to the information associated with that specific version:

```
version.created_at
version.changes
version.number
```

You should note that a single version will not typically store an entire snapshot of the model's state at that point in time, only the changes that were made to get to that state. To see the big picture, use `revert_to`.
