### ISSUE TITLE
Is there a reason to create an initial version?

### ISSUE THREAD

**Issue by sthapit** [laserlemon/vestal_versions#10]
What's the point of the current version 1 if changes = nil?  I propose that versions only get created when a model gets updated.

**Comment by laserlemon** [comment]
In the beginning, the initial version contained a snapshot of all the current model attributes. In my infinite foolishness, I thought this important historical information. But as it was pointed out to me (thanks snaury) that changes from the initial version are never used during reversion, I instead set `changes` to nil to save on database storage.

Now you have a great point. That whole _version_ is a waste of database storage. My only concern with scrapping it altogether is the mess it may make of the version fetching methods. On the other hand, it would be nice to do away with the `create_initial_version` method and callback.

I'll look into it (hopefully today) and update you. Thanks for the suggestion!

Steve

**Comment by laserlemon** [comment]
I've created a branch called skip-initial. Please take a look and feel free to give your feedback. I'll still need to revisit this and make sure that upgrading vestal_versions won't break reversions for models that already have an initial version in the database.

Thanks again for the suggestion and I look forward to your feedback.

**Comment by sthapit** [comment]
cool!  thanks for the fork - looks like it works.  since this makes more sense why not just make the skip-initial the main/trunk gem?  will be less confusing for users i think

**Comment by laserlemon** [comment]
Thanks for taking a look, but I still have more testing to do. I'm 90% sure that an upgrade now will break reverts for currently versioned models. Please feel free to lend a hand with testing if you have time. Thanks again!

**Comment by laserlemon** [comment]
A 1.0 release of vestal_versions is imminent and will abandon creation of version-1 versions. Records having no versions will have a `version` of 1 and the next update will save a version-2 version record.

1.0 development also addresses backwards compatibility with existing version-1 versions. 1.0 also introduces a bunch of other features (including version tagging, which is the one exception to the skip-initial-version rule). Stay tuned and I'll get 1.0 development up here for your review.

**Comment by sthapit** [comment]
sounds great!  look forward to testing and using it :)

**Comment by jerome** [comment]
+1

Got 2 millions entries, only 0,1% will maybe change. I don't want to millions of unused rows in versions table :)

**Comment by laserlemon** [comment]
Closing this issue in anticipation of 1.0.

**Comment by sthapit** [comment]
since this is a legacy issue, may i suggest to keep vestal_versions at version 0.8.3 so it doesn't break for current users and start a brand new project on github.  win win :)  fresh starts are good in my opinion and rails badly needs a top class versioning gem - i'm pretty sure vestal versions is the best available so doing it now might be better than before it's being used on thousands more projects.

you could even brainstorm a new name with all your users and hopefully come up with something equally clever to vestal versions...

**Comment by laserlemon** [comment]
The 1.0 branch is backwards compatible and can deal with the existence of initial versions just fine. In fact, I believe the new version will be backwards-compatible across the board so luckily, I don't think it'll be necessary to create a new project (which I think could be pretty disorienting).

Plus, I find it hard to believe there's another name out there that's equally clever to vestal_versions. ;)
