### ISSUE TITLE
Where did version 1.2.3 go ?

### ISSUE THREAD

**Issue by robertleelittleiii** [laserlemon/vestal_versions#105]
Hey there.

  We are running Rails 3.1.11 and Ruby 1.8.7.  We were using the 1.2.3 release, but that version has disappeared from github.   I don't want to go back to 1.0.2 and we are not moving to ruby 1.9.3 yet and vestal versions 2.0 seems to require 1.9.3.

Please Help!

Thanks,

Rob Little.

**Comment by midas** [comment]
I am researching this and will get back with you ASAP.

**Comment by laserlemon** [comment]
There never was a version 1.2.3 of vestal_versions from the canonical source. There looks to be a version 1.2.3 gem released from a fork. See:
- http://rubygems.org/gems/geothird_vestal_versions/versions
- https://github.com/geothird/vestal_versions
