### ISSUE TITLE
Forcibly increment version?

### ISSUE THREAD

**Issue by nilesh** [laserlemon/vestal_versions#11]
Is there a way to force a version increment without any changes?

This could be useful in cases when related models' versions are kept in sync even if only one of them has changed. This could be an easy way to track complex associations across versions--just get the related objects with the same version numbers.

**Comment by laserlemon** [comment]
Hi Nilesh,

Right now, there is not. I'll consider adding that to 1.0 development, but currently the best way to keep models in sync through complex associations is by using a datetime rather than a version number for reversion. This way, any given model can be a part of multiple complex associations without having to keep up with the version numbers of any of them.

Steve

**Comment by nilesh** [comment]
Hello Steve,

By 'datetime' you mean using a field, say 'touched_at', in each of the models to bump up their versions, right?

**Comment by laserlemon** [comment]
No, what I mean to say is that you don't have to bump up a model's version number artificially to somehow keep it in sync with other models. If it's currently:

```
Thu Oct 22 09:15:14 -0400 2009
```

and you want to bump a model's version along with a bunch of related models, you can just skip that process and use the above datetime value as your reference when you revert. For instance:

```
@model.revert_to(1.day.ago) # or
@model.revert_to(Time.parse("Thu Oct 22 09:15:14 -0400 2009"))
```

Dates and times are something that every model can "understand" without having to be synced up in any way. Hope that helps!

**Comment by laserlemon** [comment]
Also, if you do need to create a blank version (no changes), you can call the `create_version` method directly from within your model. This method isn't really meant to be forward-facing so it's a private method, but

```
@model.send(:create_version)
```

should do the trick to simply bump up a version number.

**Comment by nilesh** [comment]
ah, yes, that makes sense. I keep on versioning individual models separately and use a timestamp as the binding attribute to all of them when I want to revert to an earlier 'changeset'. Got it. And thanks for the `create_version` trick.
