### ISSUE TITLE
Remove specific version

### ISSUE THREAD

**Issue by lailsonbm** [laserlemon/vestal_versions#13]
It would be very nice if we could remove an specific version from database, in order to maintain it lean.
For example, I have a model that is _versioned_ by month. This way, I have one version for 01/2009, 02/2009 and so on. But people can update an old month record, and it duplicates the version for a given month. For example, if I have a 11/2009 version and update the 02/2009 version, it gets duplicated on the database. The solution I found now is remove the 02/2009 version (and shift all previous versions' numbering to maintain the straight sequence), so it stays there only once. This solution could be incorporated to vestal_versions.

**Comment by laserlemon** [comment]
While I see how this may be useful is some cases, I have a couple concerns:

Updating a past version is like putting a kink in a hose. The chain of version changes should be uninterrupted or we risk breaking the reversion functionality. To change a past version properly, we would want version branching, but vestal_versions is intended to store a linear history of changes. Also, the concept of renumbering existing versions seems disorienting to me. Version numbers are meant to be a constant version reference more than they're meant to be a gapless sequence.
