### ISSUE TITLE
Identify versions by String

### ISSUE THREAD

**Issue by lailsonbm** [laserlemon/vestal_versions#14]
Instead of relying only on numbers for versioning, vestal_versions could identify versions by some optional unique string too. This would speed up a lot of scenarios, when we have to iteratively revert to previous versions in order to test some object property; with labels, we could just make one query to database if that property is uniquely tied to the label.

**Comment by laserlemon** [comment]
I have a 1.0 branch in the works that implements version tagging, which I believe does exactly what you're describing. Check it out and let me know if you have any suggestions.
