### ISSUE TITLE
show_version

### ISSUE THREAD

**Issue by matiaskorhonen** [laserlemon/vestal_versions#16]
Could you please implement a #show_version method that could return a specific version of a model?

For example:

```
>> u = User.create(:first_name => 'Steve', :last_name => 'Richert')
=> #<User first_name: "Steve", last_name: "Richert">
>> u.version
=> 1
>> u.update_attribute(:first_name, 'Stephen')
=> true
>> u.show_version(:first)
=> #<User first_name: "Steve", last_name: "Richert">
>> u.show_version(2).name
=> "Stephen Richert"
```

This sort of functionality would be especially handy when one needs to compare the differences (if any) between two versions across multiple attributes.

**Comment by laserlemon** [comment]
Hi Matias,

If I understand you correctly, that's just what the `revert_to` method is for. Please check out that functionality and let me know if there's something additional you had in mind. And sorry about the lack of documentation. That's something I plan to remedy soon. Thanks!

Steve
