### ISSUE TITLE
versions removed when using is_paranoid

### ISSUE THREAD

**Issue by zacheryph** [laserlemon/vestal_versions#17]
if you try using vestal_versions with is_paranoid, the version history gets removed no matter what.

tried is_paranoid before versioned in model and vice versa.  the outcome is still the same. i technically still have a record in the master table and yet all of the history is removed.

**Comment by laserlemon** [comment]
That's intentional. Versions are set to delete when the parent record is destroyed. Version 1.0 will allow for better control over that behavior.
