### ISSUE TITLE
Version records are == if their number is the same, but their versioned model is different

### ISSUE THREAD

**Issue by davidlee** [laserlemon/vestal_versions#19]
<pre>
 v1 = Version.new(:number => 1, :versioned_type => "Foo")
 v2 = Version.new(:number => 1, :versioned_type => "Bar")
 v1 == v2 
 # => true
</pre>

suggest something like the patch at:
 http://github.com/davidlee/vestal_versions/commit/9a1318a36bd1ace4a6db1569e933bc61d97fab84

cheers.
DL

**Comment by laserlemon** [comment]
David,

Thanks for the suggestion. I went about this slightly differently, but it has made its way into the version 1.0 release today. Thanks again,

Steve
