### ISSUE TITLE
Diff

### ISSUE THREAD

**Issue by Florian95** [laserlemon/vestal_versions#2]
Hi,

Good plugin. I already use it. But i want to add a diff method. Its in your roadmap ?

Thank you,
Florian

**Comment by laserlemon** [comment]
Hi Florian,

Yes, it's on the docket. I'm working out the best way to implement it. If you have any suggestions, please let me know or feel free to fork the repo. Thanks for the feedback,

Steve

**Comment by laserlemon** [comment]
Version 1.0 was just released and diff support didn't make the cut. There hasn't been enough (vocal) need for it, but please feel free to take on this feature yourself! I'd welcome the addition if it could significantly cut down on storage without sacrificing too much performance.

**Comment by nickjones** [comment]
I'm considering adding this to my project and would absolutely love a diff feature.

**Comment by cmelbye** [comment]
I'd love a diff feature, because this is being used for a wiki and it would be nice to see changes between versions.

**Comment by rnck** [comment]
I definitely need a diff feature, too. Please put it in.

Thanks!

Heiko

**Comment by asoules** [comment]
+1

**Comment by bhellman1** [comment]
+1
