### ISSUE TITLE
Optional versioning

### ISSUE THREAD

**Issue by pyromaniac** [laserlemon/vestal_versions#20]
Hello, can you add option for versioned function to disable callbacks? I don't need to create versions every time i edit my recodrs. I want to trigger versioning when i need. Thanks.

**Comment by laserlemon** [comment]
Version 1.0 of vestal_versions was just released and has you covered in all sorts of ways. There are additional `if` and `unless` options for determining whether or not a new version record should be created. In addition, you can make an exception to those rules with the new `skip_version` block as shown in the README.
