### ISSUE TITLE
How to get a complete object at a given version without reverting?

### ISSUE THREAD

**Issue by kandadaboggu** [laserlemon/vestal_versions#28]
I have a `Company` model as shown below: 

```
class Company < ActiveRecord::Base
   versioned
end

c = Company.create(:name => "ABC", :address => "XYZ") # version 1
c.update_attribute(:zip => "3545")                    # version 2
c.update_attribute(:address => "PQR")                 # version 3
c.update_attribute(:phone => "546456")                # version 4
```

How do I get the complete `Company` object at version 2? I tried to use `c.versions.at(2)`. That returns me an `VestalVersions` object.

**Comment by laserlemon** [comment]
That's exactly what reverting is for. Why are you trying to avoid using:

```
c.revert_to(2)
```

Without using `revert_to!` (note the bang), the reversion won't be saved. So you can simply `revert_to(4)` to bring it right back.

**Comment by brentgreeff** [comment]
this info would be useful on the project homepage I think.

**Comment by dmfrancisco** [comment]
I also have this problem. I would like to list all the versions of an object. Something like this doesn't work:

```
myvar.versions.each do |version|
    myvar.revert_to(version.number)
    puts myvar.name
    all_versions << myvar
end
```

The prints show the right version name but the array _all_versions_ only contains objects equal to the newest version (corresponding to the last _revert_to_).

The only solution I see is to clone _myvar_ but that isn't ideal because I'll have new objects with only one version.

**Comment by adamcooper** [comment]
Here is a helper that we are currently using in our project:

```
def versions_for(object, to_version = 1)
  current_version = object.version
  current_version.downto(to_version).each do |version|
    object.revert_to(version)

    vestal_version = object.versions.at(version)
    if vestal_version.nil?
      object.updated_at = object.created_at
    else
      object.updated_at = vestal_version.created_at
    end

    yield object, version
  end
  object.reload
end
```

If memory serves me I initially tried to capture it off into a hash but found this worked and it made my calling code a bit easier to read.

**Comment by dmfrancisco** [comment]
Works like a charm :) Thank you

**Comment by bhellman1** [comment]
so, given a version # how do you obtain that record as a object w/o saving?

**Comment by adamcooper** [comment]
You just need to call 'revert_to' and pass in the specific version.

```
object.revert_to(version)
```

then `object` will be at a specific version.
