### ISSUE TITLE
Plugin not work with disabled pluralize_table_names

### ISSUE THREAD

**Issue by traxanos** [laserlemon/vestal_versions#4]
I use,
ActiveRecord::Base.pluralize_table_names = false

the plugin won't work

**Comment by laserlemon** [comment]
Hi Marco,

In that case, did you change the migration generated by vestal_versions to create a table named "version"?

Steve

**Comment by laserlemon** [comment]
Version 1.0 of vestal_versions is in progress and will address this issue by allowing for the version class to be customized with a user-defined class that inherits from the default version model.

**Comment by laserlemon** [comment]
Closing this issue in anticipation of 1.0.

**Comment by laserlemon** [comment]
The 1.0 release today should open up the ability to specify your own `Version` model where you can specify your own table name. Please see the README for more information.
