### ISSUE TITLE
Versioned associations?

### ISSUE THREAD

**Issue by jpemberthy** [laserlemon/vestal_versions#43]
I'd like to be sure if vestal_versions does support versioned associations (it seems like it doesn't) before switching out to another versioning gem that can support versioned associations e.g => has_versioning. I haven't looked at the code yet but I couldn't find anything related with versioned associations from the readme file or this issues section. Help would be appreciated!

**Comment by medihack** [comment]
I am very interested in this, too. Does it feature versioned associations?

**Comment by bradbirnbaum** [comment]
We also are interested in this
