### ISSUE TITLE
Need an option to ignore attributes

### ISSUE THREAD

**Issue by aussiegeek** [laserlemon/vestal_versions#5]
I have attributes such as last_logged_in_at which I don't want to be versioned. Can we get this down the track?

**Comment by sthapit** [comment]
i totally agree - i also am looking for a way to exclude a column.  simply versioned does this by letting you specify: simply_versioned :exclude => :awkward_column

**Comment by sthapit** [comment]
i ended up creating a simple fork to allow for this.  you can now do things like versioned :only => [:title, :details] or versioned :except => :state and so on.  the project is at http://github.com/sthapit/vestal_versions

**Comment by laserlemon** [comment]
Alan (aussiegeek), thanks for bringing this to my attention. And another big thanks to sthapit for taking on the development of this feature. I've merged sthapit's changes (squashed and slightly modified) and have bumped the version to 0.8.0. Thanks again!

Steve
