### ISSUE TITLE
Generator not working? (Rails3)

### ISSUE THREAD

**Issue by lwille** [laserlemon/vestal_versions#54]
When executing "rails generate vestal_versions", I get the following error:
    Could not find generator vestal_versions.

The vestal_versions generator is not listed in the output of "rails generate --help".

rails -v
    ruby -Rails 3.0.0.rc
ruby -v
    ruby 1.9.2dev (2010-07-11 revision 28618) [x86_64-linux]
rvm -v
    rvm 0.1.44 by Wayne E. Seguin (wayneeseguin@gmail.com) [http://rvm.beginrescueend.com/]

**Comment by lwille** [comment]
Ouch! Just updated Rails to 3.0.1 and it works :-D

**Comment by adamcooper** [comment]
lwille, 

I am pretty sure that laserlemon's fork doesn't play nice with Rails 3.  There are a couple issues that are not compatible.

I have been keeping an updated version of the gem compatible with Rails 3 here:
http://github.com/adamcooper/vestal_versions

My company has started using and is committed to maintaining this gem.
