### ISSUE TITLE
incremental_version_changes not detected for serialized as Array attributes

### ISSUE THREAD

**Issue by rockrep** [laserlemon/vestal_versions#56]
Currently using alexcrichton's fork.

I have a class which has a mediumtext attribute, serialized as Array. i.e.

class MyClass < ActiveRecord::Base
  serialize :my_attribute, Array
  after_initialize :ensure_array

  def ensure_array
    my_attribute = [] unless my_attribute && my_attribute.is_a?(Array)
  end

end

Repro Scenario:
mc = MyClass.new(:my_attribute => %w(a b c)  # true
mc.version == 1  # true
mc.my_attribute[1] = "x"  # "x"
mc.send(:incremental_version_changes) # {}
mc.save! # true
mc.reload.my_attribute # ["a", "x", "c"]
mc.version == 2 # false, mc.version == 1

If alternatively, I use clone the Array and set it as an Array directly, incremental_version_changes detects the change correctly

mc = MyClass.new(:my_attribute => %w(a b c)  # true
mc.version == 1  # true
tmp = my_attribute.clone
tmp[1] = "x"
mc.my_attribute = tmp
mc.send(:incremental_version_changes) # not empty
mc.save! # true
mc.reload.my_attribute # ["a", "x", "c"]
mc.version == 2 # true

**Comment by adamcooper** [comment]
This is actually a limitation of the ActiveRecord dirty tracking.  Serialized attributes, and other attributes can't detect in place changes.  VestalVersions depends on the dirty tracking in ActiveRecord..

What you need to do here is mark the method `my_attribute_will_change!` before modifying it.

Excerpt from ActiveRecord::Dirty docs (http://apidock.com/rails/ActiveRecord/Dirty)

```
# Before modifying an attribute in-place:
person.name_will_change!
person.name << 'by'
person.name_change    # => ['uncle bob', 'uncle bobby']
```

Hopefully that helps.

Cheers,
Adam

**Comment by rockrep** [comment]
Thanks for the clarification Adam.   - Michael
