### ISSUE TITLE
Combined changes between many versions

### ISSUE THREAD

**Issue by jlecour** [laserlemon/vestal_versions#6]
Hi,

I needed to show differences between 2 versions, but not necessarly adjacent.

Let's say I have a Page model, with a `title`, a `content`, a `published` boolean, a `published_at` date and a `synced_at` date. The `synced_at` is relevant because that's my 'from' date.

I've made some changes and I get this : 

```
>> p = Page.first
=> #<Page id: 1, title: "Bonjour tout le monde", content: "Ceci est un super Hello World!", published: true, published_at: "2009-09-12 12:30:56", created_at: "2009-09-11 14:16:08", updated_at: "2009-09-21 15:00:47", synced_at: "2009-09-11 18:16:08">
>> p.versions
=> [#<Version id: 1, versioned_id: 1, versioned_type: "Page", changes: nil, number: 1, created_at: "2009-09-11 14:16:08">, #<Version id: 2, versioned_id: 1, versioned_type: "Page", changes: {"updated_at"=>[Fri Sep 11 14:16:08 UTC 2009, Mon Sep 21 14:17:28 UTC 2009], "published"=>[false, true], "published_at"=>[nil, Sat Sep 12 12:30:56 UTC 2009]}, number: 2, created_at: "2009-09-12 12:30:56">, #<Version id: 3, versioned_id: 1, versioned_type: "Page", changes: {"updated_at"=>[Mon Sep 21 14:17:28 UTC 2009, Mon Sep 21 14:18:26 UTC 2009], "title"=>["Hello World!", "Hello Everyone, including the World"]}, number: 3, created_at: "2009-09-15 10:18:26">, #<Version id: 4, versioned_id: 1, versioned_type: "Page", changes: {"updated_at"=>[Tue Sep 15 10:18:26 UTC 2009, Mon Sep 21 15:00:47 UTC 2009], "title"=>["Hello Everyone, including the World", "Bonjour tout le monde"]}, number: 4, created_at: "2009-09-21 15:00:47">]
```

I want to know what has been changed since the last sync (hence the `synced_at`date).
With  just a few minutes playing in the Rails console, I tried this :

```
>> changes = {}
=> {}
>> p.versions.between(p.synced_at,Time.now).each {|v| v.changes.each{|k,v| changes[k] ? changes[k][1] = v[1] : changes[k] = v } unless v.changes.nil? }
=> (…)
>> changes
=> {"updated_at"=>[Fri Sep 11 14:16:08 UTC 2009, Mon Sep 21 15:00:47 UTC 2009], "title"=>["Hello World!", "Bonjour tout le monde"], "published"=>[false, true], "published_at"=>[nil, Sat Sep 12 12:30:56 UTC 2009]}
```

There, I can see those changes all, in one hash, just like there has been only one change since the last sync.

I'm sure there is something better to return the hash without using the changes Hash, but I'm not as good as this in Ruby.

I don't know if it might be useful and if it deserves to be included in the plugin, that's up to you.

**Comment by jlecour** [comment]
And with this
    class Page < ActiveRecord::Base
      versioned

```
  def self.modified_after_sync()
    sql = "SELECT p.* FROM pages AS p LEFT JOIN versions AS v ON v.versioned_id = p.id WHERE v.created_at >= p.synced_at GROUP BY p.id ORDER BY v.created_at DESC"

    find_by_sql(sql)
  end

end
```

I can get Pages that have been updated after their last sync.

**Comment by laserlemon** [comment]
Jérémy,

Thanks for the suggestion. I think that's a good addition. That sort of change aggregation is already done in the `revert_to` method. I'll work on extracting that out to its own method.

Steve

**Comment by laserlemon** [comment]
I've added a public instance method on the versioned model called `changes_between` that accepts two arguments and returns the aggregated changes between the two corresponding versions. Committed and bumped to 0.7.0. Thanks again.

**Comment by jlecour** [comment]
Cool. I'm glad I could do a little something. What you did with my modest idea is way better than my proposal. It's gona be super usefull. Thank you
