### ISSUE TITLE
how can I use with rails 2.3.8?

### ISSUE THREAD

**Issue by angelacode** [laserlemon/vestal_versions#62]
It currently has a dependency on activesupport 3.0...is there a way I can use it with 2.3.8?

**Comment by carpodaster** [comment]
[v1.0.2](https://github.com/laserlemon/vestal_versions/tree/v1.0.2) is Rails 2.3 compatible. `config.gem 'vestal_versions',  :version => '~> 1.0'` in your `config/environment.rb` will get you there. Or if you're using bundler, as your comment in #65 suggests, go with `gem 'vestal_versions',  '1.0.2'` in your `Gemfile`.

**Comment by berga** [comment]
version 1.0.2 uses column t.text :changes in versions table so in Rails 2.3.14 it run into this error:

ActiveRecord::UnknownAttributeError: unknown attribute: changes

is it possible to fix it in a 1.0.3 version compatible with rails 2.3.x?

**Comment by carpodaster** [comment]
berga, I'm using 1.0.2 w/ Rails 2.3.14 and I don't get any errors so I don't think it's related to a probable VV incompatibility with 2.3.14. Can you stack trace the error to see its origin? I don't know if the schema changed for the Rails 3 version but if so, make sure your environment loads the correct VV gem if you got the newer gem installed on the system (and if you don't use rvm gemsets or bundler).

**Comment by berga** [comment]
hi, I was using config.gem 'vestal_versions', :version => '1.0.2' and freezed gem under vendor/gems.
I've forked and pushed my refactoring to use column named "modifications" under: https://github.com/berga/vestal_versions and tag: 1.0.3 and this is working for me.
info: I'm using ree 1.8.7

**Comment by laserlemon** [comment]
No plans to have Rails 2 compatibility going forward. Thanks!
