### ISSUE TITLE
Official repository?

### ISSUE THREAD

**Issue by iamvery** [laserlemon/vestal_versions#72]
Has the official repository been moved over to @adamcooper? It would probably help everyone feel a little more comfortable using this gem if the rubygems.org namespace and such were in use by him as well. I see that he has carried on the versioning, but I naturally shy away from using anything but official repo.

**Comment by krisleech** [comment]
This confused me also.

**Comment by winston** [comment]
+1 I prefer official repo too.

**Comment by laserlemon** [comment]
Official repo is still here.
