### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by 1xch** [laserlemon/vestal_versions#78]
Within rails log: 

DEPRECATION WARNING: class_inheritable_attribute is deprecated, please use class_attribute method instead. Notice their behavior are slightly different, so refer to class_attribute documentation first. (called from prepare_versioned_options at /home/qx/.rvm/gems/ruby-1.9.2-p180/bundler/gems/vestal_versions-6273df533f85/lib/vestal_versions/options.rb:31)

**Comment by redcine** [comment]
+1 I am also getting this error.

**Comment by petecocoon** [comment]
+1 me too

**Comment by petecocoon** [comment]
You can use this _non-solution_, if you issue is only the noise output:
put 'ActiveSupport::Deprecation.silenced = true'
in config/appliction.rb

**Comment by TheHumaneClub** [comment]
+1

**Comment by jfrioux** [comment]
Same here

**Comment by tispratik** [comment]
+1 me too

**Comment by Vibhuti** [comment]
+1 me too

**Comment by brendankemp** [comment]
PR to ichiro's fork: https://github.com/ichiro101/vestal_versions/pull/2
