### ISSUE TITLE
MassAssignmentSecurity::Error when updating record in Rails 3.2.8

### ISSUE THREAD

**Issue by kidlab** [laserlemon/vestal_versions#86]
I'm using Rails 3.2.8 with the configuration:

```
config.active_record.whitelist_attributes = true
```

I got this error when updating a record:

```
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes: modifications, number, user
```

**Comment by drush** [comment]
Add this patch until it gets migrated into master @laserlemon :

module VestalVersions
  # The ActiveRecord model representing versions.
  class Version < ActiveRecord::Base
    attr_accessible :modifications, :number, :user

  end
end

**Comment by dreamr** [comment]
This is all done on the rails_3 branch

**Comment by JeanMertz** [comment]
I'm not seeing anything like this in the Rails 3 branch, and it seems those changes have been merged into Master lately?

I'm also getting this error at the moment, I use the direct Github master branch version.

**Comment by chrstphlbr** [comment]
I'm also getting this error despite using branch 'rails_3'.
Is there a fix in progress?

@drush your proposed patch isn't working for me

thanks in advance.

**Comment by hrichter** [comment]
actually the current master branch is still not containing any fix for this issue. Additionally, If you were to track deleted records and try to revert, you will notice that you need

attr_accessible :modifications, :number, :user, :reverted_from, :tag

but i think this is not very "clean", wouldn't it be better to generate the attribute list as needed, so there wouldn't be a mass assignment?

**Comment by dreamr** [comment]
So sorry, I am unavailable atm. My sailboat is stuck in Mexico after a
storm. I wont be able to look at this until later this evening or tomorrow
morning.

James OKelly

**Comment by caplod** [comment]
I temporarily fixed it with an initializer file under config/initializers/patch_vestal_versions.rb with

``` ruby
VestalVersions::Version.module_eval do     
  attr_accessible :modifications, :number, :user
end     
```

**Comment by gwincr11** [comment]
:reverted_from also seems to be affected by this bug.

**Comment by tobypinder** [comment]
+1 Confirming this issue, thanks all for the workarounds.

**Comment by xyzren** [comment]
Is this still unfixed? I am using the 1.2.3 c7aa512 version and got this problem.

**Comment by kashif-umair** [comment]
@caplod , Thank you very much for sharing the temporary patch. It saved me a lot of time and searching.

**Comment by himesh-r** [comment]
Has it been fixed?
I followed the documentation and am facing the same issue...
Patching doesnt seem good, but dont have any other choice right now.
It would be good if someone updates the thread once it is foxed :)

**Comment by wiredin** [comment]
Just ran into this issue when trying to update a record

**Comment by laserlemon** [comment]
Should be fixed in master.

**Comment by guy-silva** [comment]
We are apparently running in this issue with the current version but we are updating from rails 3.2 to 4.0.3
So checking the the https://github.com/laserlemon/vestal_versions/blob/master/lib/vestal_versions/version.rb I can see the problem is 

``` ruby
if ActiveRecord::VERSION::MAJOR == 3
  attr_accessible :modifications, :number, :user, :tag, :reverted_from
end
```

Would it be wrong to assume a fix would be 

``` ruby
if ActiveRecord::VERSION::MAJOR >= 3
  attr_accessible :modifications, :number, :user, :tag, :reverted_from
end
```

Or do you think there are more places to be fixed in order to be running on rails 4?

**Comment by midas** [comment]
Rails 4 uses https://github.com/rails/strong_parameters and attr_accessible is deprecated.  So that would not fix the issue.
